name: Python package

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'
    - name: Install dependencies
      run: |
        make install
    - name: Run tests with pytest
      run: |
        make test
    - name: Build package
      run: |
        make build
    - name: Upload wheel
      uses: actions/upload-artifact@v2
      with:
        name: wheel
        path: dist/*.whl

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
  
    steps:
    - uses: actions/checkout@v2
    - name: Download wheel
      uses: actions/download-artifact@v2
      with:
        name: wheel
        path: distwhere 
    - name: Deploy to PyPI
      run: |
        make deploy
  clean:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - uses: actions/checkout@v2
    - name: Clean temporary directories
      run: |
        make clean